@echo off
echo [GODZ] Iniciando NEXUS SUPREME AI (ChatTTS)...
start "NEXUS_AI" cmd /k "python server/godz_ai_bridge.py"
timeout /t 12
echo [GODZ] Iniciando Servidor FiveM...
artifacts\FXServer.exe +exec server.cfg